# tests/test_pm.py
import unittest
from unittest.mock import MagicMock, patch
import json

# These imports will fail initially. That's the point.
from studio.pm import ProductManager, DefaultPlanningStrategy, JsonPlanStorage

class TestProductManager(unittest.TestCase):

    def test_product_manager_orchestration(self):
        """
        Tests that ProductManager correctly uses its strategy and storage dependencies.
        """
        # 1. Arrange
        mock_strategy = MagicMock()
        mock_storage = MagicMock()

        high_level_goal = "Develop a new feature for the Analyst."
        generated_plan = {"steps": ["Define requirements", "Write tests", "Implement feature"]}

        # Configure the mock strategy to return a predefined plan
        mock_strategy.create_plan.return_value = generated_plan

        # 2. Act
        # Instantiate the ProductManager with the mocked dependencies
        pm = ProductManager(strategy=mock_strategy, storage=mock_storage)
        pm.execute(high_level_goal)

        # 3. Assert
        # Verify that the strategy was called with the correct goal
        mock_strategy.create_plan.assert_called_once_with(high_level_goal)

        # Verify that the storage was called with the plan generated by the strategy
        mock_storage.save.assert_called_once_with(generated_plan)

    @patch('builtins.open')
    @patch('json.dump')
    def test_json_plan_storage(self, mock_json_dump, mock_open):
        """
        Tests that JsonPlanStorage correctly opens a file and writes JSON.
        """
        # 1. Arrange
        storage = JsonPlanStorage(filepath="plan.json")
        plan_data = {"key": "value"}

        # 2. Act
        storage.save(plan_data)

        # 3. Assert
        mock_open.assert_called_once_with("plan.json", "w", encoding="utf-8")
        mock_json_dump.assert_called_once()
        # Check that json.dump was called with the correct data and file handle
        self.assertEqual(mock_json_dump.call_args[0][0], plan_data)

    def test_default_planning_strategy(self):
        """
        Tests the basic logic of the default planning strategy.
        """
        # 1. Arrange
        strategy = DefaultPlanningStrategy()
        goal = "Refactor module X"

        # 2. Act
        plan = strategy.create_plan(goal)

        # 3. Assert
        self.assertIn("goal", plan)
        self.assertEqual(plan["goal"], goal)
        self.assertIn("tasks", plan)
        self.assertIsInstance(plan["tasks"], list)
        # A simple check to ensure some tasks are generated
        self.assertTrue(len(plan["tasks"]) > 0)
        self.assertIn("TDD", plan["tasks"][0]["title"]) # Enforce TDD
